# Generated by Django 4.2.6 on 2023-10-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de alta')),
            ],
        ),
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('area', models.CharField(max_length=100, null=True, verbose_name='Area')),
                ('numero_placa', models.CharField(max_length=100, verbose_name='Numero de placa')),
                ('rol', models.CharField(max_length=50, null=True, verbose_name='Rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('area', models.CharField(max_length=100, null=True, verbose_name='Area')),
                ('cuit', models.CharField(max_length=100, verbose_name='Cuit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('patente', models.CharField(max_length=100, verbose_name='Patente')),
                ('vencimiento_vtv', models.DateField(verbose_name='Fecha de vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=150, null=True, verbose_name='Descripcion del área')),
                ('bomberos', models.ManyToManyField(related_name='+', through='core.Alta', to='core.bombero')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.jefe')),
            ],
        ),
        migrations.AddField(
            model_name='alta',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
        migrations.AddField(
            model_name='alta',
            name='bombero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bombero'),
        ),
    ]
