# Generated by Django 4.2.6 on 2023-11-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='bomberos',
            field=models.ManyToManyField(related_name='areas', through='core.Alta', to='core.bombero'),
        ),
        migrations.AlterField(
            model_name='area',
            name='jefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.jefe'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(unique=True, verbose_name='Patente'),
        ),
    ]
